export type FabricSearchItem = {
  id: string;
  supplier_id: string;
  supplier_name: string;
  fabric_number: string;
  composition: string | null;
  color: string | null;
  weight_gsm: number | null;
  width_cm: number | null;
  width_inches: number | null;
  unit_price: number | null;
  unit: string;
  stock_status?: "in_stock" | "temp_unavailable" | "permanently_unavailable" | null;
  restock_date?: string | null;
  description?: string | null;
  list_price?: number | null;
  disponibilita_meters?: number | null;
  api_is_available?: boolean | null;
  manual?: boolean;
  mill_line?: "loro_piana" | "solbiati" | null;
};
