export type IntegrationEventType =
  | "fabric_order.created"
  | "fabric_order.sent"
  | "fabric_order.cancelled"
  | "fabric_order.email_failed"
  | "supplier.contacts_updated"
  | "supplier.reply_logged"
  | "supplier.availability_detected"
  | "follow_up.due"
  | "awb.received"
  | "email.test_sent"
  | "price_list.imported"
  | "client.created"
  | "client.updated"
  | "client.deleted"
  | "sales_order.created"
  | "sales_order.deleted"
  | "sales_order.fabric_lines_added"
  | "sales_order.fabric_lines_updated"
  | "sales_order.fabric_lines_removed"
  | "sales_order.fabric_lines_printed"
  | "sales_order.fabric_lines_print_cleared"
  | "sales_order.fabric_order_requested"
  | "sales_order.client_fields_healed"
  | "fabric_receiving.testing_reset"
  | "fabric_receiving.settled"
  | "fabric_receiving.defect_reported"
  | "fabric_receiving.defect_acknowledged"
  | "fabric_receiving.defect_resolved"
  | "fabric.transferred"
  | "pattern_job.created"
  | "pattern_job.updated"
  | "pattern_fitting.completed"
  | "pattern_revision.created"
  | "pattern_job.ready_for_cutting"
  | "production.scan"
  | "invoice.sent"
  | "invoice.created"
  | "invoice.updated"
  | "sales_client_details.updated"
  | "sales_client_photo.uploaded"
  | "sales_fitting.created"
  | "sales_fitting.updated"
  | "sales_order.milestone_updated"
  | "custom_fabric.created"
  | "supabase.auth_unhealthy";

export interface IntegrationEvent<T = Record<string, unknown>> {
  event: IntegrationEventType;
  timestamp: string;
  source: "erp" | "zapier" | "api";
  data: T;
}
